triggers:
- name: ontology-plan
  project: migiration-demo
  configFilePath: cloudbuild-plan.yaml
  eventType: push
  includedGitRefs: ^refs/heads/master$
  includedFiles:
  - "ontology/**"
  - "scripts/**"
  - "cloudbuild-plan.yaml"
  serviceAccount: projects/migiration-demo/serviceAccounts/656669276990-compute@developer.gserviceaccount.com
- name: ontology-apply
  project: migiration-demo
  configFilePath: cloudbuild-apply.yaml
  eventType: push
  includedGitRefs: ^refs/heads/master$
  includedFiles:
  - "ontology/**"
  - "scripts/**"
  - "cloudbuild-apply.yaml"
  serviceAccount: projects/migiration-demo/serviceAccounts/656669276990-compute@developer.gserviceaccount.com
  disabled: true
